### ISSUE TITLE
Temporary console log issues - part 2

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#1058]
1) If a job is cancelled before it is assigned to an agent then the console log is empty. As a result on ui , console log shows up as blank and in artifacts tab blank console log is attached which does not make too much sense. Earlier behaviour was that console log shows message - "Console log for this job is unavailable as it may have been purged by Go or deleted externally". Also artifacts tab would show message - "
Artifacts for this job instance are unavailable as they may have been purged by Go or deleted externally. Re-run the stage or job to generate them again." 

2) If job is cancelled by the Go-server then following message shows up -

**Go cancelled this job as it has not generated any console output for more than 1 minute(s)15:28:47.094 [go] Start to execute cancel task: Kills child processes**
15:28:47.195 [go] Task is cancelled
15:28:47.343 [go] Job completed Simple-console-testing/12/defaultStage/1/defaultJob on arikag [/var/lib/go-agent-1]

Note: lines in bold are sticking to each other

3) Let a pipeline P have 3 jobs. And let all the jobs run once (counter 1). Now rerun say job1. Look at the artifact location - ../pipelines/P/1/defaultStage/2. Note that you can see job2 and job3 present there (they are empty though) apart from job1 even though they were not rerun. Note: there is no effect on ui due to this.

4) Console.log appears twice as artifact when a job is rescheduled

**Comment by arikagoyal** [comment]
Issue 3 fixed on 15.1.0(1863-42e58c22aefd03)

**Comment by chopraapooja** [comment]
Point 4) has been fixed by #1089

**Comment by rajiesh** [comment]
Issues 1 & 2 mentioned here are not fixed - verified on 15.3.0-2698(369b66909146ad43e7291032a27a19454252ac8f). Issue 3 & 4 are fixed

**Comment by arvindsv** [comment]
Closing as stale.
