### ISSUE TITLE
The GoCD Debian repo uses SHA-1

### ISSUE THREAD

**Issue by brettcave** [gocd/gocd#2612]
##### Issue Type
- Feature enhancement 
##### Summary

APT no longer supports SHA-1. On new versions of APT, a warning is given when SHA-1 is used for signing, e.g.

```
$ cat /etc/apt/sources.list.d/thoughtworks.list 
deb https://download.go.cd /
$  apt-get --version
apt 1.2.12 (amd64)
$ sudo apt-get update
...
W: https://download.go.cd/InRelease: Signature by key 322259C82D3082B3E32AEC2ED8843F288816C449 uses weak digest algorithm (SHA1)
```

More details:
https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/

SHA-1 support will be completely disabled by Jan 1 2017, according to [this post](https://wiki.debian.org/Teams/Apt/Sha1Removal):

**Comment by ketan** [comment]
Thank you for the heads up. Since 16.9 is due sometime this week, we'll target to get this resolved in time for 16.10.

**Comment by brettcave** [comment]
Great, thanks @ketan

**Comment by timoa** [comment]
This error still the same for the last 16.11 with an Ubuntu 16.04 LTS.

It works well with the previous Ubuntu LTS (14.04 LTS)

**Comment by ketan** [comment]
Thank you for bringing this to notice, it slipped through the cracks. I'm going to address this on priority.

**Comment by ketan** [comment]
Re-opening for @rajiesh to verify on the experimental repository, before we roll this out to the production repo

**Comment by ketan** [comment]
To test —

* Create a `Vagrantfile` with the contents below —

    ```ruby
    Vagrant.configure("2") do |config|
      config.vm.box = "ubuntu/xenial64"

      config.vm.provision "shell", inline: <<-SHELL
        echo "deb http://download.go.cd/experimental /" | sudo tee /etc/apt/sources.list.d/gocd.list
        curl https://download.go.cd/GOCD-GPG-KEY.asc | sudo apt-key add -
        apt-get update
        apt-get install -y openjdk-jre8-headless
        apt-get install -y go-agent
      SHELL
    end
    ```
* Run `vagrant up --provider virtualbox`

To verify with the production apt server, run `vagrant destroy -f` and change the apt url in the vagrant file to be `http://download.go.cd`.

**Comment by ketan** [comment]
Closing issue. I don't see the warning message anymore. The `InRelease` file is now signed using SHA512 digest.

**Comment by dziemba** [comment]
The fix in https://github.com/gocd/build_utilities/commit/97ba1bc14a28751f65e20bdae79dd5838ea9a331 only changes the algorithm for `InRelease`, but not for `Release.gpg`. 

Can we also please upgrade the algorithm for `Release.gpg`?

**Comment by YoSijo** [comment]
I have to agree with @dziemba  here: "Release.gpg" still works with an outdated algorithm.
Please upgrade the algorithm for Release.gpg.

**Comment by ibnc** [comment]
This issue has been addressed. The lines referenced in the build_utilities repo are no longer used, and need to be cleaned up. 

signing is now happening here: https://github.com/gocd/codesigning/blob/master/rakelib/apt.rake#L22-L23
