### ISSUE TITLE
Not able to access GOCD after changing credentials 

### ISSUE THREAD

**Issue by narasimhaprasadd** [gocd/gocd#4853]
##### Issue Type

- Bug Report

##### Summary

I had saved the login information in GO CD. Upon updating my credentials I am unable to access the pipelines page. After inspecting the page, It seemed to be a recursive redirects between Login and Pipeline pages.

###### Basic environment details

* Go Version: `Go Version: 18.6.0 (6853-3541529f60044fec297f42efce08ca65d14651ad).`
* Browser vendor and version (if relevant): `Google Chrome`

##### Steps to Reproduce

1. Login to GO CD
2. Update the login credentials 
3. Try accessing GO CD

##### Expected Results
I should be able to see the pipeline  page, If not, should be redirected to Login page to enter my new credentials

##### Actual Results
I see this issue after few seconds of pinging the server
```GO CD redirected you too many times.```

**Comment by varshavaradarajan** [comment]
Related: https://github.com/gocd/gocd/issues/3915

**Comment by arvindsv** [comment]
Well, since it is happening on 18.6, maybe it is different?

@narasimhaprasadd Can you try in an incognito window (or a new browser profile) where the cookies are not present? Do you use web-based auth (google oauth, etc) or just password-based authentication?

**Comment by narasimhaprasadd** [comment]
Sorry I missed to update that. 
>Can you try in an incognito window (or a new browser profile) where the cookies are not present? 
Yes, I am able to access it from Incognito.

> Do you use web-based auth (google oauth, etc) or just password-based authentication?
I am trying password based auth.

**Comment by narasimhaprasadd** [comment]
Accidentally closed!

**Comment by arvindsv** [comment]
@narasimhaprasadd Thank you for confirming that. I'll add it to 18.7 milestone, to be reproduced and fixed in the upcoming release. For now, clearing cookies for the GoCD server's domain (can be done through the browser's inspect feature) might be a way to get past this. We will update this issue when there's a fix available for you to potentially test on.

Thanks!

**Comment by ketan** [comment]
@narasimhaprasadd — we have a fix available. Can you check https://github.com/gocd/gocd/issues/4872#issuecomment-399827027 and respond?

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7117-1709149e6946f9cec95e4a8e914a47c7806f0672). @narasimhaprasadd - Please let know if issue is not resolved for you
