### ISSUE TITLE
When a task plugin throws a runtime exception, the stacktrace does not get logged in agent log

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#786]
Plugin-author can catch it and log it on plugin logs, but if that is not the case, plugin users find it difficult to investigate any issue in the plugin.

Builder.logException uses LOGGER.error(e), using LOGGER.error(e.getMessage(), e) should fix this.

**Comment by mdaliejaz** [comment]
Fixed as part of #750

**Comment by arikagoyal** [comment]
Verified on 15.1.0(1587-dcefa94a22ae98). The issue is still not resolved.  There is still no details of the plugin code in the stack trace to help out plugin authors. Ex - If runtime exception is thrown by email notifier sample plugin, it gives following in go-server.log -

2015-03-10 12:47:53,980  WARN [70@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: working.email.notifier.runtime.exception
java.lang.RuntimeException: Interaction with plugin with id 'working.email.notifier.runtime.exception' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["runtime exception - email notifier"]}']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["runtime exception - email notifier"]}'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)

Runtime exception thrown by sample curl plugin looks like following in go-agent.log -

java.lang.RuntimeException: Interaction with plugin with id 'new.curl.task.runtime.exception' implementing 'task' extension failed while requesting for 'execute'. Reason: [null]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExecutor.execute(JsonBasedTaskExecutor.java:45)
        at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.executeTask(PluggableTaskBuilder.java:97)
        at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:74)
        at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder$1.execute(PluggableTaskBuilder.java:71)
        at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExtension.execute(JsonBasedTaskExtension.java:55)
        at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.execute(TaskExtension.java:66)
        at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.build(PluggableTaskBuilder.java:71)
        at com.thoughtworks.go.domain.builder.Builder.build(Builder.java:51)
        at com.thoughtworks.go.remote.work.Builders.build(Builders.java:63)
        at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:212)
        at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:187)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:149)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:95)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)

**Comment by arvindsv** [comment]
Related to #119 as well (not directly).

**Comment by arvindsv** [comment]
Related to #884 as well (not directly).

**Comment by arvindsv** [comment]
No activity. Stale. Closing.
