### ISSUE TITLE
Mac Agent has an incorrect PATH variable values.

### ISSUE THREAD

**Issue by nikita-leonov** [gocd/gocd#852]
PATH variable for job executed by agent does not contain the same PATH values that actual go agent user has. So for example user's values are:
```
gocdagent$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
```
while when job executed values are:
```
[Debug Information] Environment variable PATH: /usr/bin:/bin:/usr/sbin:/sbin
```

There was no explicitly defined redefinition of PATH variable anywhere in go.cd configuration on my side.
Is it expected behavior? Where and how it could be reconfigured to include /usr/local/bin as well?

**Comment by arvindsv** [comment]
Hey @nikita-leonov,

I think these are related:
https://groups.google.com/d/topic/go-cd/t98Mr1nI0Q0/discussion
https://github.com/gocd/gocd/issues/796#issuecomment-69052019

I'm closing this issue as a duplicate. This should definitely get solved soon, as a part of #796. Thanks for your patience. Apple has changed how an application can change its PATH environment variable, and they seem to be systematically removing ways to do that.

I would set a pipeline-level environment variable to get past this issue, till the Mac app is changed to allow this.

Regards,
Aravind

**Comment by nikita-leonov** [comment]
We found temporary workaround. Apparently when Agent executed /etc/profile is not run. While running agent from shell like following /Applications/Go\ Agent.app/Contents/MacOS/go-agent PATH applied properly.

ps I believe setting PATH on pipeline is a bad practice. As such operation will required all over xxx pipelines.

**Comment by arvindsv** [comment]
> ps I believe setting PATH on pipeline is a bad practice. As such operation will required all over xxx pipelines.

Completely agree. That's why I mentioned it as a workaround, just in case you need to. I wouldn't do that too, but just starting the app from Go Agent.app, it doesn't seem to have any way to set the PATH, unfortunately.

**Comment by nikita-leonov** [comment]
Also would it be possible to keep this issue open until it is actually fixed? It sounds strange that referenced PR is not directly related to an issue and there is no indication of existing problem in a product in an issue list.

**Comment by arvindsv** [comment]
Of course. Reopening it.

**Comment by nykolaslima** [comment]
@nikita-leonov Can you explain in more details how do you workaround this problem?

**Comment by nykolaslima** [comment]
@nikita-leonov forget it. I make it work as you explained:
`$ cd /Applications/Go\ Agent.app/`
`$ sh agent.sh`

Now it's working. Thank you.

**Comment by nykolaslima** [comment]
@jyotisingh Is this issue solved? The solution that @nikita-leonov gave is a temporally workaround.

**Comment by arvindsv** [comment]
@nykolaslima: Yes, it is fixed as a part of the new installers for the upcoming release, 15.1. You can try out an experimental build, say 15.1.0-1770, of it on http://go.cd/download (try both the server and agent installers, please, for it to work).

I've updated the documentation for it, through a pull request, but it is not accepted yet. [Here it is](https://github.com/gocd/documentation/pull/100/files#diff-82957b86e030429e1b7833133af53c8aR60).

**Comment by nykolaslima** [comment]
Nice! Thank you!

**Comment by nikita-leonov** [comment]
@arvindsv just out of curiosity, do you know when 15.1 will be released? I see a lot of features fixed in it, but there is still not stable 15.x release available for public.

**Comment by arvindsv** [comment]
Hi @nikita-leonov, it's planned for this month.

**Comment by nikita-leonov** [comment]
Thanks! Looking forward for a new release. You developing a great tool guys, appreciate your effort!

**Comment by Hippoom** [comment]
It seems that the bug still exists for 16.2.1. 

I ran into the similar issue that the PATH is not set correctly when I launch Go Agent from Launchpad. But it is fine if I run the agent from terminal by 

```
cd /Applications/Go\ Agent.app/Contents/MacOS
./go-agent
```

**Comment by arvindsv** [comment]
Have you tried [this](https://docs.go.cd/current/installation/install/agent/osx.html#overriding-default-startup-arguments-and-environment)? Mac apps don't have the ability to control PATH, unfortunately. So, it'll need to be overridden as mentioned in the link. That should work.

**Comment by Hippoom** [comment]
It works with overrides.env, thank you @arvindsv
